# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Reporte.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 591)
        MainWindow.setFixedSize(894,591)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_principal = QtWidgets.QFrame(self.centralwidget)
        self.frame_principal.setStyleSheet("background-color: rgb(255, 253, 252);")
        self.frame_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_principal.setObjectName("frame_principal")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_principal)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_menu = QtWidgets.QFrame(self.frame_principal)
        self.frame_menu.setMinimumSize(QtCore.QSize(450, 0))
        self.frame_menu.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_menu)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_cintillo = QtWidgets.QFrame(self.frame_menu)
        self.frame_cintillo.setMinimumSize(QtCore.QSize(0, 140))
        self.frame_cintillo.setMaximumSize(QtCore.QSize(16777215, 140))
        self.frame_cintillo.setStyleSheet("image: url(:/cintillos/cintillo-cuadrado.png);")
        self.frame_cintillo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_cintillo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cintillo.setObjectName("frame_cintillo")
        self.verticalLayout_2.addWidget(self.frame_cintillo)
        self.stackedWidget_izq = QtWidgets.QStackedWidget(self.frame_menu)
        self.stackedWidget_izq.setObjectName("stackedWidget_izq")
        self.page_izq1 = QtWidgets.QWidget()
        self.page_izq1.setObjectName("page_izq1")
        self.layoutWidget = QtWidgets.QWidget(self.page_izq1)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 431, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_ultimoSismo = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_ultimoSismo.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_ultimoSismo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_ultimoSismo.setStyleSheet("QPushButton {\n"
"    background-color: rgb(208, 225, 232);\n"
"    border-radius: 15px;\n"
"    border: none;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(208, 225, 250);\n"
"}")
        self.pushButton_ultimoSismo.setObjectName("pushButton_ultimoSismo")
        self.horizontalLayout_2.addWidget(self.pushButton_ultimoSismo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButton_busquedaManual = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_busquedaManual.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_busquedaManual.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_busquedaManual.setStyleSheet("QPushButton {\n"
"    background-color: rgb(208, 225, 232);\n"
"    border-radius: 15px;\n"
"    border: none;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(208, 225, 250);\n"
"}")
        self.pushButton_busquedaManual.setObjectName("pushButton_busquedaManual")
        self.horizontalLayout_3.addWidget(self.pushButton_busquedaManual)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.pushButton_ultimos10 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_ultimos10.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_ultimos10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_ultimos10.setStyleSheet("QPushButton {\n"
"    background-color: rgb(208, 225, 232);\n"
"    border-radius: 15px;\n"
"    border: none;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(208, 225, 250);\n"
"}")
        self.pushButton_ultimos10.setObjectName("pushButton_ultimos10")
        self.horizontalLayout_4.addWidget(self.pushButton_ultimos10)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.pushButton_busquedaFecha = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_busquedaFecha.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_busquedaFecha.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_busquedaFecha.setStyleSheet("QPushButton {\n"
"    background-color: rgb(208, 225, 232);\n"
"    border-radius: 15px;\n"
"    border: none;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(208, 225, 250);\n"
"}")
        self.pushButton_busquedaFecha.setObjectName("pushButton_busquedaFecha")
        self.horizontalLayout_5.addWidget(self.pushButton_busquedaFecha)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.stackedWidget_izq.addWidget(self.page_izq1)
        self.page_izq5 = QtWidgets.QWidget()
        self.page_izq5.setObjectName("page_izq5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_izq5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem13 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem13)
        self.pushButton_regresarImprimir = QtWidgets.QPushButton(self.page_izq5)
        self.pushButton_regresarImprimir.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButton_regresarImprimir.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton_regresarImprimir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_regresarImprimir.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 217, 179);\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(85, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 201, 157);\n"
"}")
        self.pushButton_regresarImprimir.setObjectName("pushButton_regresarImprimir")
        self.horizontalLayout_12.addWidget(self.pushButton_regresarImprimir)
        spacerItem14 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem14)
        self.pushButton_imprimirReporte = QtWidgets.QPushButton(self.page_izq5)
        self.pushButton_imprimirReporte.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButton_imprimirReporte.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton_imprimirReporte.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_imprimirReporte.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 217, 179);\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(85, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 201, 157);\n"
"}")
        self.pushButton_imprimirReporte.setObjectName("pushButton_imprimirReporte")
        self.horizontalLayout_12.addWidget(self.pushButton_imprimirReporte)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.stackedWidget_izq.addWidget(self.page_izq5)
        self.page_izq2 = QtWidgets.QWidget()
        self.page_izq2.setObjectName("page_izq2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_izq2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem16 = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem16, 0, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(97, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem17, 1, 0, 1, 1)
        self.lineEdit_ID = QtWidgets.QLineEdit(self.page_izq2)
        self.lineEdit_ID.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_ID.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_ID.setStyleSheet("background-color: rgb(208, 225, 232);\n"
"border: none;\n"
"border-radius: 10px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_ID.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.gridLayout_2.addWidget(self.lineEdit_ID, 1, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(97, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem18, 1, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 98, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem19, 2, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem20 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem20)
        self.pushButton_RegresarID = QtWidgets.QPushButton(self.page_izq2)
        self.pushButton_RegresarID.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_RegresarID.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_RegresarID.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_RegresarID.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 217, 179);\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(85, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 201, 157);\n"
"}")
        self.pushButton_RegresarID.setObjectName("pushButton_RegresarID")
        self.horizontalLayout_8.addWidget(self.pushButton_RegresarID)
        spacerItem21 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem21)
        self.pushButton_continuarID = QtWidgets.QPushButton(self.page_izq2)
        self.pushButton_continuarID.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_continuarID.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_continuarID.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_continuarID.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 217, 179);\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(85, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 201, 157);\n"
"}")
        self.pushButton_continuarID.setObjectName("pushButton_continuarID")
        self.horizontalLayout_8.addWidget(self.pushButton_continuarID)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem22)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 3, 0, 1, 3)
        spacerItem23 = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem23, 4, 1, 1, 1)
        self.stackedWidget_izq.addWidget(self.page_izq2)
        self.page_izq3 = QtWidgets.QWidget()
        self.page_izq3.setObjectName("page_izq3")
        self.tableWidget_ultimos10 = QtWidgets.QTableWidget(self.page_izq3)
        self.tableWidget_ultimos10.setGeometry(QtCore.QRect(20, 30, 371, 301))
        self.tableWidget_ultimos10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_ultimos10.setAutoFillBackground(False)
        self.tableWidget_ultimos10.setStyleSheet("QTableWidget{\n"
"    border: none;\n"
"    font-size: 12pt;\n"
"    background-color: rgb(255, 213, 193);\n"
"gridline-color:(255,255,255)\n"
"}\n"
"\n"
"QHeaderView::Section {\n"
"    background-color: rgb(255, 131, 73);\n"
"    border: 1px solid rgb(255,255,255);\n"
"color:rgb(255,255,255);\n"
"font-size: 12pr\n"
"}")
        self.tableWidget_ultimos10.setWordWrap(True)
        self.tableWidget_ultimos10.setCornerButtonEnabled(True)
        self.tableWidget_ultimos10.setObjectName("tableWidget_ultimos10")
        self.tableWidget_ultimos10.setColumnCount(3)
        self.tableWidget_ultimos10.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_ultimos10.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_ultimos10.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_ultimos10.setHorizontalHeaderItem(2, item)
        self.tableWidget_ultimos10.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_ultimos10.horizontalHeader().setDefaultSectionSize(123)
        self.tableWidget_ultimos10.horizontalHeader().setHighlightSections(False)
        self.widget = QtWidgets.QWidget(self.page_izq3)
        self.widget.setGeometry(QtCore.QRect(0, 360, 421, 32))
        self.widget.setObjectName("widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem24 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem24)
        self.pushButton_regresar10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_regresar10.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_regresar10.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_regresar10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_regresar10.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 217, 179);\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(85, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 201, 157);\n"
"}")
        self.pushButton_regresar10.setObjectName("pushButton_regresar10")
        self.horizontalLayout_9.addWidget(self.pushButton_regresar10)
        spacerItem25 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem25)
        self.pushButton_continuar10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_continuar10.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_continuar10.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_continuar10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_continuar10.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 217, 179);\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(85, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 201, 157);\n"
"}")
        self.pushButton_continuar10.setObjectName("pushButton_continuar10")
        self.horizontalLayout_9.addWidget(self.pushButton_continuar10)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem26)
        self.stackedWidget_izq.addWidget(self.page_izq3)
        self.page_izq4 = QtWidgets.QWidget()
        self.page_izq4.setObjectName("page_izq4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_izq4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame = QtWidgets.QFrame(self.page_izq4)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem27 = QtWidgets.QSpacerItem(111, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem27, 1, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(111, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem28, 3, 2, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(111, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem29, 1, 2, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem30, 2, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_dia = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dia.setFont(font)
        self.label_dia.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dia.setObjectName("label_dia")
        self.verticalLayout_5.addWidget(self.label_dia)
        spacerItem31 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem31)
        self.spinBox_dia = QtWidgets.QSpinBox(self.frame)
        self.spinBox_dia.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_dia.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_dia.setFont(font)
        self.spinBox_dia.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_dia.setStyleSheet("QSpinBox {\n"
"    padding:3px; \n"
"    border-radius: 7px;\n"
"    border: 1px solid rgb(255, 182, 134); ;\n"
"}")
        self.spinBox_dia.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_dia.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox_dia.setMinimum(1)
        self.spinBox_dia.setMaximum(31)
        self.spinBox_dia.setObjectName("spinBox_dia")
        self.verticalLayout_5.addWidget(self.spinBox_dia)
        self.gridLayout.addLayout(self.verticalLayout_5, 5, 1, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(111, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem32, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem33 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem33)
        self.pushButton_regresarFecha = QtWidgets.QPushButton(self.frame)
        self.pushButton_regresarFecha.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_regresarFecha.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_regresarFecha.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_regresarFecha.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 217, 179);\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(85, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 201, 157);\n"
"}")
        self.pushButton_regresarFecha.setObjectName("pushButton_regresarFecha")
        self.horizontalLayout_7.addWidget(self.pushButton_regresarFecha)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem34)
        self.pushButton_continuarFecha = QtWidgets.QPushButton(self.frame)
        self.pushButton_continuarFecha.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_continuarFecha.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_continuarFecha.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_continuarFecha.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 217, 179);\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(85, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 201, 157);\n"
"}")
        self.pushButton_continuarFecha.setAutoDefault(False)
        self.pushButton_continuarFecha.setObjectName("pushButton_continuarFecha")
        self.horizontalLayout_7.addWidget(self.pushButton_continuarFecha)
        spacerItem35 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem35)
        self.gridLayout.addLayout(self.horizontalLayout_7, 7, 0, 1, 3)
        spacerItem36 = QtWidgets.QSpacerItem(111, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem36, 5, 2, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem37, 0, 1, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_Ano = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Ano.setFont(font)
        self.label_Ano.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Ano.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ano.setObjectName("label_Ano")
        self.verticalLayout_7.addWidget(self.label_Ano)
        spacerItem38 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem38)
        self.spinBox_ano = QtWidgets.QSpinBox(self.frame)
        self.spinBox_ano.setMinimumSize(QtCore.QSize(150, 30))
        self.spinBox_ano.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_ano.setFont(font)
        self.spinBox_ano.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_ano.setStyleSheet("QSpinBox {\n"
"    padding:3px; \n"
"    border-radius: 7px;\n"
"    border: 1px solid rgb(255, 182, 134);\n"
"}")
        self.spinBox_ano.setFrame(False)
        self.spinBox_ano.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_ano.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_ano.setSpecialValueText("")
        self.spinBox_ano.setMinimum(2000)
        self.spinBox_ano.setMaximum(2100)
        self.spinBox_ano.setProperty("value", 2024)
        self.spinBox_ano.setObjectName("spinBox_ano")
        self.verticalLayout_7.addWidget(self.spinBox_ano)
        self.gridLayout.addLayout(self.verticalLayout_7, 1, 1, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(111, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem39, 3, 0, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem40, 4, 1, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem41, 6, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_mes = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_mes.setFont(font)
        self.label_mes.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mes.setObjectName("label_mes")
        self.verticalLayout_6.addWidget(self.label_mes)
        spacerItem42 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem42)
        self.comboBox_mes = QtWidgets.QComboBox(self.frame)
        self.comboBox_mes.setMinimumSize(QtCore.QSize(86, 30))
        self.comboBox_mes.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_mes.setFont(font)
        self.comboBox_mes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_mes.setStyleSheet("QComboBox {   /* Cambia el color de fondo */\n"
"    border: 1px solid #a0a0a0;    /* Cambia el color del borde */\n"
"    padding: 3px;                 /* Ajusta el espaciado interno */\n"
"    min-width: 6em;    \n"
"border: 1px solid rgb(255, 182, 134)   ;\n"
"border-radius: 7px;        /* Ajusta el ancho mínimo */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 20px;                  /* Ajusta el ancho del botón desplegable */\n"
"}\n"
"")
        self.comboBox_mes.setObjectName("comboBox_mes")
        self.comboBox_mes.addItem("")
        self.comboBox_mes.addItem("")
        self.comboBox_mes.addItem("")
        self.comboBox_mes.addItem("")
        self.comboBox_mes.addItem("")
        self.comboBox_mes.addItem("")
        self.comboBox_mes.addItem("")
        self.comboBox_mes.addItem("")
        self.comboBox_mes.addItem("")
        self.comboBox_mes.addItem("")
        self.comboBox_mes.addItem("")
        self.comboBox_mes.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox_mes)
        self.gridLayout.addLayout(self.verticalLayout_6, 3, 1, 1, 1)
        self.horizontalLayout_10.addWidget(self.frame)
        self.stackedWidget_izq.addWidget(self.page_izq4)
        self.verticalLayout_2.addWidget(self.stackedWidget_izq)
        self.horizontalLayout.addWidget(self.frame_menu)
        self.frame_logo = QtWidgets.QFrame(self.frame_principal)
        self.frame_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_logo.setObjectName("frame_logo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_logo)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget_der = QtWidgets.QStackedWidget(self.frame_logo)
        self.stackedWidget_der.setObjectName("stackedWidget_der")
        self.page_der1 = QtWidgets.QWidget()
        self.page_der1.setObjectName("page_der1")
        self.frame_contenedorLogo = QtWidgets.QFrame(self.page_der1)
        self.frame_contenedorLogo.setGeometry(QtCore.QRect(30, 160, 331, 221))
        self.frame_contenedorLogo.setStyleSheet("image: url(:/cintillos/Logo-Funvisis.png);\n"
"border-style : solid;\n"
"border-color: rgb(255, 170, 0);\n"
"border-width: 3px;\n"
"padding: 10px;")
        self.frame_contenedorLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contenedorLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenedorLogo.setObjectName("frame_contenedorLogo")
        self.stackedWidget_der.addWidget(self.page_der1)
        self.page_der2 = QtWidgets.QWidget()
        self.page_der2.setObjectName("page_der2")
        self.stackedWidget_der.addWidget(self.page_der2)
        self.verticalLayout_3.addWidget(self.stackedWidget_der)
        self.horizontalLayout.addWidget(self.frame_logo)
        self.horizontalLayout_11.addWidget(self.frame_principal)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_izq.setCurrentIndex(0)
        self.stackedWidget_der.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_ultimoSismo.setText(_translate("MainWindow", "Último Sismo"))
        self.pushButton_busquedaManual.setText(_translate("MainWindow", "Búsqueda Manual (ID)"))
        self.pushButton_ultimos10.setText(_translate("MainWindow", "Últimos 10 Sismos"))
        self.pushButton_busquedaFecha.setText(_translate("MainWindow", "Búsqueda por Fecha"))
        self.pushButton_regresarImprimir.setText(_translate("MainWindow", "Regresar"))
        self.pushButton_imprimirReporte.setText(_translate("MainWindow", "Imprimir Reporte"))
        self.lineEdit_ID.setPlaceholderText(_translate("MainWindow", "Inserte ID"))
        self.pushButton_RegresarID.setText(_translate("MainWindow", "Regresar"))
        self.pushButton_continuarID.setText(_translate("MainWindow", "Continuar"))
        item = self.tableWidget_ultimos10.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.tableWidget_ultimos10.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hora"))
        item = self.tableWidget_ultimos10.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ID"))
        self.pushButton_regresar10.setText(_translate("MainWindow", "Regresar"))
        self.pushButton_continuar10.setText(_translate("MainWindow", "Continuar"))
        self.label_dia.setText(_translate("MainWindow", "Dia"))
        self.pushButton_regresarFecha.setText(_translate("MainWindow", "Regresar"))
        self.pushButton_continuarFecha.setText(_translate("MainWindow", "Continuar"))
        self.label_Ano.setText(_translate("MainWindow", "Año"))
        self.label_mes.setText(_translate("MainWindow", "Mes"))
        self.comboBox_mes.setPlaceholderText(_translate("MainWindow", "Mes"))
        self.comboBox_mes.setItemText(0, _translate("MainWindow", "Enero"))
        self.comboBox_mes.setItemText(1, _translate("MainWindow", "Febrero"))
        self.comboBox_mes.setItemText(2, _translate("MainWindow", "Marzo"))
        self.comboBox_mes.setItemText(3, _translate("MainWindow", "Abril"))
        self.comboBox_mes.setItemText(4, _translate("MainWindow", "Mayo"))
        self.comboBox_mes.setItemText(5, _translate("MainWindow", "Junio"))
        self.comboBox_mes.setItemText(6, _translate("MainWindow", "Julio"))
        self.comboBox_mes.setItemText(7, _translate("MainWindow", "Agosto"))
        self.comboBox_mes.setItemText(8, _translate("MainWindow", "Septiembre"))
        self.comboBox_mes.setItemText(9, _translate("MainWindow", "Octubre"))
        self.comboBox_mes.setItemText(10, _translate("MainWindow", "Noviembre"))
        self.comboBox_mes.setItemText(11, _translate("MainWindow", "Diciembre"))

import imagenes_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
